# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_cards', '0002_payment_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype', models.ImageField(height_field=150, upload_to='insurance', verbose_name='Логотип компании')),
                ('name', models.CharField(max_length=100, verbose_name='Название страховой компании')),
                ('url', models.URLField(verbose_name='Ссылка на Е-ОСАГО')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
            },
        ),
    ]
